# Preload is required before applying the wallpaper
preload = /home/minhngon/Pictures/Wallpapers/1.jpeg

# LG Monitor
wallpaper {
    monitor = HDMI-A-1
    path = /home/minhngon/Pictures/Wallpapers/1.jpeg
    fit_mode = cover
}

# Samsung Odyssey
wallpaper {
    monitor = DP-2
    path = /home/minhngon/Pictures/Wallpapers/1.jpeg
    fit_mode = cover
}

# Optional settings
splash = false
ipc = on
